"""Remove user_id from donations and update relationships

Revision ID: 5ae2d2d3d16f
Revises: 831d1f4793e8
Create Date: 2025-04-29 23:02:10.974460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae2d2d3d16f'
down_revision = '831d1f4793e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        # Removed drop_constraint line because constraint name does not exist in SQLite
        # batch_op.drop_constraint('fk_donations_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_donations_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
